logging:
  level:
    com:
      baomidou:
        mybatisplus: info
    org:
      mybatis=INFO:
# MongoDB
makeflow:
  data:
    dataType: mysql
    mongo:
      replicaSet: 127.0.0.1:27017
      dbname: makeflow
      connectionsPerHost: 200
      threadsAllowedToBlockForConnectionMultiplier: 10
      maxWaitTime: 4000
      connectTimeout: 4000
      socketTimeout: 5000
      autoConnectRetry: true
      readPreference: primaryPreferred
      username: root
      password: root
      authdb: admin
    mysql:
      druid-data-source:
        username: root
        password: root
        url: jdbc:mysql://127.0.0.1:3306/make_flow?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    server:
      # 单机：stand-alone
      host: 127.0.0.1
      password: 123456
      port: 6379
      database: 0
      type: stand-alone
      #     哨兵：sentinel ；主从： 或者 master-slave  集群：cluster
      #        master: mymaster
      #        nodes: 172.16.39.18:26376,172.16.39.18:26377,172.16.39.18:26378
      #        password: csp172@eb5g
      #        database: 0
      #        type: sentinel
      #     集群：cluster
      #    nodes: 172.16.39.18:26376,172.16.39.18:26377,172.16.39.18:26378
      #    password: csp172@eb5g
      #    database: 0
      #    type: cluster
      #获取锁最长等待时间,单位秒
      waitTime: 10
      #锁过期最长时间，单位秒
      leaseTime: 10